platform :ios, ‘9.0’
target 'SuiEGo-01_Test' do

pod 'AFNetworking'
pod 'BlocksKit'
pod 'CocoaLumberjack'
pod 'Masonry'
pod 'MBProgressHUD'
pod 'MJExtension'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'TPKeyboardAvoiding'
pod 'MLTransition'
pod 'REMenu'
pod 'RESideMenu'
pod 'LLSlideMenu'
pod 'RETableViewManager'
pod 'Canvas'
pod 'UITableView+FDTemplateLayoutCell'
pod 'FLAnimatedImage'
end